// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGHkl0Ata7Ez5LZYoxA8l486zRQ8IUtT8',
    appId: '1:312578586474:web:3fc461176074b1440ad713',
    messagingSenderId: '312578586474',
    projectId: 'habit-m-13e24',
    authDomain: 'habit-m-13e24.firebaseapp.com',
    storageBucket: 'habit-m-13e24.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqmm3JnFAcVxcr2AdAe0lNt3-P_vlSKJw',
    appId: '1:312578586474:android:d4b5bd0a162bf0ac0ad713',
    messagingSenderId: '312578586474',
    projectId: 'habit-m-13e24',
    storageBucket: 'habit-m-13e24.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNOy37smSw3QtxBT9oC1sXoqSkfQq6Nb0',
    appId: '1:312578586474:ios:6ffe775f882c463f0ad713',
    messagingSenderId: '312578586474',
    projectId: 'habit-m-13e24',
    storageBucket: 'habit-m-13e24.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNOy37smSw3QtxBT9oC1sXoqSkfQq6Nb0',
    appId: '1:312578586474:ios:6ffe775f882c463f0ad713',
    messagingSenderId: '312578586474',
    projectId: 'habit-m-13e24',
    storageBucket: 'habit-m-13e24.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGHkl0Ata7Ez5LZYoxA8l486zRQ8IUtT8',
    appId: '1:312578586474:web:3fc461176074b1440ad713',
    messagingSenderId: '312578586474',
    projectId: 'habit-m-13e24',
    authDomain: 'habit-m-13e24.firebaseapp.com',
    storageBucket: 'habit-m-13e24.firebasestorage.app',
  );
}
